version: "3.8"

services:
  core_users:
    container_name: core_users
    build:
      context: ./services/backend/core
      dockerfile: Dockerfile-user
    environment:
      - SQLALCHEMY_DATABASE_URI=
    ports:
      - 5002:5002
    

  web:
    container_name: web
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    # volumes:
    # # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
    #   - web-app-mount:/app/app
    #   - web-app-node-modules-mount:/app/app/node_modules
    depends_on:
      - backend_users

  scraper_ymlu:
    container_name: scraper_ymlu
    build:
      context: ./services/backend/scrapers
      dockerfile: Dockerfile-Ymlu
    ports:
      - 8080:8080

  scraper_good:
    container_name: scraper_good
    build:
      context: ./services/backend/scrapers
      dockerfile: Dockerfile-Goodrich
    ports:
      - 8081:8081

  # swagger:
  #   container_name: swagger
  #   build:
  #     context: ./doc
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8077:8079
  
  # swagger-editor:
  #   image: swaggerapi/swagger-editor
  #   container_name: "swagger-editor-container"
  #   ports:
  #     - "8078:8079"
  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: "swagger-ui-container"
  #   ports:
  #     - "8079:8079"
  #   volumes:
  #     - ./doc:/usr/share/nginx/html/doc
  #   environment:
  #     SWAGGER_JSON: doc/openapi.yml

