version: "3.8"

services:
  core_users:
    container_name: core_users
    build:
      context: ./services/backend/core
      dockerfile: Dockerfile-user-dev
    environment:
      - SQLALCHEMY_DATABASE_URI=<DB_URI>
    ports:
      - 5002:5002
    

  web:
    container_name: web
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    # volumes:
    # # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
    #   - web-app-mount:/app/app
    #   - web-app-node-modules-mount:/app/app/node_modules
    depends_on:
      - core_users

  scraper_ymlu:
    container_name: scraper_ymlu
    build:
      context: ./services/backend/scrapers
      dockerfile: Dockerfile-Ymlu-dev
    ports:
      - 8080:8080

  scraper_good:
    container_name: scraper_good
    build:
      context: ./services/backend/scrapers
      dockerfile: Dockerfile-Goodrich-dev
    ports:
      - 8081:8081

  scraper_kmtc:
    container_name: scraper_kmtc
    build:
      context: ./services/backend/scrapers
      shm_size: '1gb'
      dockerfile: Dockerfile-Kmtc-dev
    shm_size: '1gb'
    ports:
      - 8082:8082
  
  scraper_one:
    container_name: scraper_one
    build:
      context: ./services/backend/scrapers
      shm_size: '1gb'
      dockerfile: Dockerfile-One-dev
    shm_size: '1gb'
    ports:
      - 8083:8083



