# for viewAllShipments.py (NOT able to test API endpoints bc cant seem to import invokes.py on my end)

FROM python:3.11

#cx-Oracle fails to install via alpine (smaller image)
# FROM python:3.12.0a4-alpine3.17

# oracle installation 

RUN mkdir app
WORKDIR /app
ARG CACHEBUST=8
COPY src/requirements.txt .
COPY src/viewAllShipments.py .
RUN mv viewAllShipments.py app.py

#for invoking microservice calls within app
COPY src/invokes.py .
COPY src/obtainIp.py .
ENV prod=0

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV TZ="Asia/Singapore"
ENV PYTHONUNBUFFERED=1



EXPOSE 5010

# start the server
CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0",  "--port=5010"]