FROM python:3.11

#cx-Oracle fails to install via alpine (smaller image)
# FROM python:3.12.0a4-alpine3.17

# oracle installation 

RUN mkdir app
WORKDIR    /opt/oracle

RUN        apt-get update && apt-get install -y libaio1 wget unzip 

            # #for ARM64
            RUN wget https://download.oracle.com/otn_software/linux/instantclient/191000/instantclient-basiclite-linux.arm64-19.10.0.0.0dbru.zip 
            RUN unzip instantclient-basiclite-linux.arm64-19.10.0.0.0dbru.zip 
            RUN rm -f instantclient-basiclite-linux.arm64-19.10.0.0.0dbru.zip 

            #for X64
            # RUN wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip 
            # RUN unzip instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip 
            # RUN rm -f instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip 

            RUN cd /opt/oracle/instantclient* 
            RUN rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci 
            RUN echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf 
            RUN ldconfig

WORKDIR /app
ARG CACHEBUST=82267
COPY user.py .
COPY requirements.txt .
COPY obtainIp.py . 
RUN mv user.py app.py

#parsed during running of build command 
ARG db 
#obtained from arg db
ENV SQLALCHEMY_DATABASE_URI=${db}

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV TZ="Asia/Singapore"
ENV PYTHONUNBUFFERED=1

EXPOSE 5002

# start the server
# CMD [ "python", "app.py" ]
CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0",  "--port=5002"]
