FROM python:3.11
# FROM python:3.12.0a4-alpine3.17

WORKDIR /app
COPY ../requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV TZ="Asia/Singapore"
ENV PYTHONUNBUFFERED=1

ARG CACHEBUST=1

COPY ../vessel_location.py .
RUN mv vessel_location.py app.py

#for invoking microservice calls within app
COPY ../invokes.py .
COPY ../obtainIp.py .

#local machine inter container communication
ENV prod=1

EXPOSE 5014

# start the server
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5014"]

