FROM python:3.11

#cx-Oracle fails to install via alpine (smaller image)
# FROM python:3.12.0a4-alpine3.17

# oracle installation 

RUN mkdir app
WORKDIR    /opt/oracle

RUN        apt-get update && apt-get install -y libaio1 wget unzip 

            # #for ARM64
            RUN wget https://download.oracle.com/otn_software/linux/instantclient/191000/instantclient-basiclite-linux.arm64-19.10.0.0.0dbru.zip 
            RUN unzip instantclient-basiclite-linux.arm64-19.10.0.0.0dbru.zip 
            RUN rm -f instantclient-basiclite-linux.arm64-19.10.0.0.0dbru.zip 

            #for X64
            # RUN wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip 
            # RUN unzip instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip 
            # RUN rm -f instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip 

            RUN cd /opt/oracle/instantclient* 
            RUN rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci 
            RUN echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf 
            RUN ldconfig

WORKDIR /app
COPY user.py .
COPY requirements.txt . 
COPY obtainIp.py .
RUN mv user.py app.py

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV TZ="Asia/Singapore"
ENV SQLALCHEMY_DATABASE_URI=oracle://wg:wgdemo*()@202.73.56.175:1521/efprod

EXPOSE 5002

# start the server
# CMD [ "python", "user.py" ]
CMD [ "python", "-m" , "flask", "run",  "--port=5002"]