
FROM python:3.11

#cx-Oracle fails to install via alpine (smaller image)
# FROM python:3.12.0a4-alpine3.17

# oracle installation 

RUN mkdir app
WORKDIR /app
COPY src/requirements.txt .
ARG CACHEBUST=6
COPY src/unloading_status.py .
RUN mv unloading_status.py app.py

COPY src/invokes.py .
COPY src/obtainIp.py .

ENV prod=0

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV TZ="Asia/Singapore"
ENV PYTHONUNBUFFERED=1

EXPOSE 5013

# start the server
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5013"]