FROM python:3.11
# FROM python:3.12.0a4-alpine3.17

WORKDIR /app
COPY src/requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV TZ="Asia/Singapore"
ENV PYTHONUNBUFFERED=1

ARG CACHEBUST=1

COPY src/vessel_location.py .
RUN mv vessel_location.py app.py

#for invoking microservice calls within app
COPY src/invokes.py .
COPY src/obtainIp.py .

#parsed during running of build command 
ARG VESSEL_API_KEY
ARG LOCATION_API_KEY
ARG GMAPS_API_KEY

#obtained from arg db
ENV VESSEL_API_KEY=${VESSEL_API_KEY}
ENV LOCATION_API_KEY=${LOCATION_API_KEY}
ENV GMAPS_API_KEY = ${GMAPS_API_KEY}

#local machine inter container communication
ENV prod=1

EXPOSE 80

# start the server
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0", "--port=80"]

