# for complex_scraper.py

FROM python:3.11

#cx-Oracle fails to install via alpine (smaller image)
# FROM python:3.12.0a4-alpine3.17

# oracle installation 

RUN mkdir app
WORKDIR /app
ARG CACHEBUST=5
COPY src/requirements.txt .
COPY src/notification_complex.py .
RUN mv notification_complex.py app.py

#for invoking microservice calls within app
COPY src/invokes.py .
COPY src/obtainIp.py .

#parsed during running of build command 
ARG twilio_sid
ARG twilio_token

#obtained from arg
ENV twilio_sid=${twilio_sid}
ENV twilio_token=${twilio_token}

#used to run prod service discovery
ENV prod=1

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV TZ="Asia/Singapore"
ENV PYTHONUNBUFFERED=1

EXPOSE 80

# start the server
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0", "--port=80"]