FROM python:3.11

#change arch to amd64 or arm64
ARG VERSION=109.0.5414.74-0ubuntu0.18.04.14
ARG ARCH=arm64
ARG URLBASE=https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+files

RUN mkdir app 
WORKDIR /chromium

#download and install
RUN wget ${URLBASE}/chromium-codecs-ffmpeg_${VERSION}_${ARCH}.deb 
RUN wget ${URLBASE}/chromium-codecs-ffmpeg-extra_${VERSION}_${ARCH}.deb 
RUN wget ${URLBASE}/chromium-browser_${VERSION}_${ARCH}.deb 
RUN wget ${URLBASE}/chromium-chromedriver_${VERSION}_${ARCH}.deb 
RUN apt-get update 
RUN apt-get install -y ./chromium-codecs-ffmpeg_${VERSION}_${ARCH}.deb 
RUN apt-get install -y ./chromium-codecs-ffmpeg-extra_${VERSION}_${ARCH}.deb 
RUN apt-get install -y ./chromium-browser_${VERSION}_${ARCH}.deb 
RUN apt-get install -y ./chromium-chromedriver_${VERSION}_${ARCH}.deb 
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /app
# copying the neccessary script
COPY requirements.txt .
COPY goodrichScraper.py .
RUN mkdir creds 
COPY ./creds/creds_goodrich.py ./creds
RUN mv goodrichScraper.py app.py

# upgrade pip and install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 80

CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0",  "--port=80"]