FROM python:3.11
ARG CACHEBUST2=69
#change arch to amd64 or arm64
ARG VERSION=109.0.5414.74-0ubuntu0.18.04.14
ARG ARCH=arm64
ARG URLBASE=https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+files

WORKDIR /chromium

#download and install
RUN wget ${URLBASE}/chromium-codecs-ffmpeg_${VERSION}_${ARCH}.deb \
&& wget ${URLBASE}/chromium-codecs-ffmpeg-extra_${VERSION}_${ARCH}.deb \
&& wget ${URLBASE}/chromium-browser_${VERSION}_${ARCH}.deb \
&& wget ${URLBASE}/chromium-chromedriver_${VERSION}_${ARCH}.deb \
&& apt-get update \
&& apt-get install -y ./chromium-codecs-ffmpeg_${VERSION}_${ARCH}.deb \
&& apt-get install -y ./chromium-codecs-ffmpeg-extra_${VERSION}_${ARCH}.deb \
&& apt-get install -y ./chromium-browser_${VERSION}_${ARCH}.deb \
&& apt-get install -y ./chromium-chromedriver_${VERSION}_${ARCH}.deb \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /app
ARG CACHEBUST=56
# copying the neccessary scripts
COPY src/requirements.txt .
COPY src/kmtcScraper.py .
RUN mv kmtcScraper.py app.py

# upgrade pip and install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1

EXPOSE 80

CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0",  "--port=80"]