version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x install-terraform.sh configure-named-profile.sh terraform-deploy.sh ../services/backend/core/buildandpush.sh  ../services/backend/scrapers/buildandpush.sh ../services/frontend/buildandpush.sh # make all scripts executable
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com #ecr login
      - ./install-terraform.sh # install terraform
      - ./configure-named-profile.sh # configure named profile

  build:
    commands:
      - ../services/backend/core/buildandpush.sh #core backend images
      - ../services/backend/scrapers/buildandpush.sh #scraper backend images
      - ./terraform-deploy.sh #deploy all infra & apps